basicplayback/build.gradle, build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS dependency to 1.3.0 and add maven as repository.
=> Update IVS release to 1.3.0

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
=> Update IVS release to 1.3.3

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
=> Update IVS version to 1.4.0

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS player version to 1.4.1
=> Update IVS version to 1.4.1

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS player version to 1.5.0
=> Update IVS version to 1.5.0

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS player version to 1.5.1
=> Update IVS version to 1.5.1

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS player version to 1.6.0
=> Update IVS version to 1.6.0

basicplayback/build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
Update IVS player version to 1.7.0
=> Update IVS version to 1.7.0

basicplayback/build.gradle, build.gradle, customui/dependencies.gradle, quizdemo/dependencies.gradle
- Add project properties to provide custom Maven repository URL and player
version
- Remove unused flatDir repository
=> Add project properties

build.gradle
=> Update IVS version to 1.10.0

build.gradle
=> Update IVS version to 1.13.0

build.gradle
*Issue #, if available:*
Update IVS version to 1.14.0
=> Update IVS version to 1.14.0

build.gradle
=> Update IVS version to 1.16.0

build.gradle
=> Update IVS version to 1.17.0

README.md, quizdemo/src/main/java/com/amazonaws/ivs/player/quizdemo/common/Configuration.kt
=> Update Quiz demo stream URL

build.gradle
=> Update IVS version to 1.18.0

build.gradle
=> Update IVS version to 1.20.0

build.gradle
=> Update IVS version to 1.21.0

basicplayback/src/main/java/com/amazonaws/ivs/player/basicplayback/MainActivity.kt, customui/src/main/java/com/amazonaws/ivs/player/customui/viewModel/MainViewModel.kt, quizdemo/src/main/java/com/amazonaws/ivs/player/quizdemo/viewModels/MainViewModel.kt
Use Player's Factory API to create players in demo activities
=> Use Player Factory API

build.gradle
=> Update IVS version to 1.24.0

build.gradle
=> Update IVS version to 1.25.0

build.gradle
=> Update IVS version to 1.26.0

build.gradle
=> Update IVS version to 1.28.0

build.gradle
=> Update Player to 1.30.0

build.gradle
=> Update IVS version to 1.31.0

build.gradle
=> Update IVS to version 1.32.0
